a) Escriba una función separanum(valor), que reciba un valor numérico real  y  separe  las  cantidades  en  un  vector  que  contiene: centavos, unidades, decenas, centenas,  etc.  Los centavos equivalen  a usar dos decimales redondeado al entero más cercano. Desarrolle el algoritmo usando operaciones de cociente y residuo (no use round())
SIN NUMPY

In [1]:

#creamos la función separanum que recibe un valor y hace el llamado a la funcion separanum
def solicitar_datos_y_separar():
    try:
        valor = float(input("Ingrese un valor numérico real: "))
        resultado = separanum(valor)
        print(f"Centavos: {resultado[0]}, Unidades: {resultado[1]}, Decenas: {resultado[2]}, Centenas: {resultado[3]}")
    except ValueError:
        print("Por favor, ingrese un número válido.")

# Función que separa un número en centavos, unidades, decenas, centenas, etc.
def separanum(valor):
    resultado = []
    centavos = int(valor * 100) % 100
    resultado.append(centavos)
    unidades = int(valor) % 10
    resultado.append(unidades)
    decenas = int(valor / 10) % 10
    resultado.append(decenas)
    centenas = int(valor / 100) % 10
    resultado.append(centenas)
    # Continuar este proceso para miles, decenas de miles, etc. si es necesario
    return resultado

solicitar_datos_y_separar()

Centavos: 0, Unidades: 9, Decenas: 8, Centenas: 5


es el ejercicio a) pero usando numpy

In [2]:
import numpy as np

# Creamos la función que solicita los datos y separa el número
def solicitar_datos_y_separar():
    while True:
        try:
            valor = float(input("Ingrese un valor numérico real: "))
            resultado = separanum(valor)
            print(f"Centavos: {resultado[0]}, Unidades: {resultado[1]}, Decenas: {resultado[2]}, Centenas: {resultado[3]}")
            break
        except ValueError:
            print("Por favor, ingrese un número válido.")

def separanum(valor):
    resultado = []
    valor *= 100  # Convertir a centavos
    centavos = np.mod(valor, 100)
    resultado.append(centavos)
    valor = np.floor(valor / 100)  # Pasar a unidades
    unidades = np.mod(valor, 10)
    resultado.append(unidades)
    valor = np.floor(valor / 10)  # Pasar a decenas
    decenas = np.mod(valor, 10)
    resultado.append(decenas)
    valor = np.floor(valor / 10)  # Pasar a centenas
    centenas = np.mod(valor, 10)
    resultado.append(centenas)
    # Continuar este proceso para miles, decenas de miles, etc. si es necesario
    return np.array(resultado)

solicitar_datos_y_separar()

Centavos: 16.0, Unidades: 5.0, Decenas: 3.0, Centenas: 9.0


b) Realice una función cuantasmonedas(centavos) que reciba la cantidad de centavos a entregar con monedas de 1, 5, 10, 25, 50 centavos usado la menor cantidad de monedas.

In [4]:
import numpy as np

# Creamos la función que calcula la cantidad de monedas necesarias
def cuantasmonedas(centavos):
    monedas = np.array([1, 5, 10, 25, 50])
    contadores = {moneda: 0 for moneda in monedas}

    for i in range(len(monedas)-1, -1, -1):
        while centavos >= monedas[i]:
            contadores[monedas[i]] += 1
            centavos -= monedas[i]

    return contadores

# Solicitamos la cantidad de centavos al usuario
while True:
    entrada = input("Ingrese la cantidad de centavos: ")
    try:
        centavos = int(entrada)
        if centavos < 0:
            raise ValueError
        resultado = cuantasmonedas(centavos)
        for moneda, cantidad in resultado.items():
            print(f"Monedas de {moneda} centavos: {cantidad}")
        break
    except ValueError:
        print("Entrada inválida. Por favor, ingrese un número entero positivo.")

Monedas de 1 centavos: 3
Monedas de 5 centavos: 0
Monedas de 10 centavos: 1
Monedas de 25 centavos: 0
Monedas de 50 centavos: 1


c). Realice un programa que permita crear un calendario de un mes cualquiera, conociendo el día de la semana que inicia el mes y el número de días que tiene el mes 
*** ingresar dia de la semana con nombre (ej. "Lunes , Martes, Miercoles...etc)


In [8]:
import numpy as np

# definimos los dias de la semana
dias_semana = {"Lunes": 0, "Martes": 1, "Miercoles": 2, "Jueves": 3, "Viernes": 4, "Sabado": 5, "Domingo": 6}

# solicitamos los datos al usuario
dia_inicio = input("Ingrese el día de la semana que inicia el mes Ejemplo Lunes , Martes ...: ")
num_dias = int(input("Ingrese el número de días que tiene el mes: "))

# creamos un arreglo de 42 elementos para representar el calendario
calendario = np.zeros(42, dtype=int)

# calculamos la posición de inicio y llenamos los días del mes
inicio = dias_semana[dia_inicio]
calendario[inicio:inicio+num_dias] = np.arange(1, num_dias+1)

# redimensionamos el arreglo a una matriz de 6x7
calendario = calendario.reshape(6, 7)
print(f'Dia de inicios de mes: {dia_inicio} \n  dias del mes : {num_dias}')
print(calendario)

Dia de inicios de mes: Martes 
  dias del mes : 30
[[ 0  1  2  3  4  5  6]
 [ 7  8  9 10 11 12 13]
 [14 15 16 17 18 19 20]
 [21 22 23 24 25 26 27]
 [28 29 30  0  0  0  0]
 [ 0  0  0  0  0  0  0]]
